workspace:
  base: /var/www/owncloud
  path: apps/user_ldap

branches: [master]

pipeline:
  ldap:
    image: dinkel/openldap
    detach: true
    pull: true
    environment:
      - SLAPD_DOMAIN=owncloud.com
      - SLAPD_ORGANIZATION=ownCloud
      - SLAPD_PASSWORD=admin
      - SLAPD_ADDITIONAL_MODULES=memberof

  install-server:
    image: owncloudci/core
    pull: true
    version: daily-master-qa
    db_type: sqlite
    db_name: owncloud
    db_host: mysql:3306
    db_username: owncloud
    db_password: owncloud

  owncloud-log:
    image: owncloud/ubuntu:16.04
    detach: true
    pull: true
    commands:
      - tail -f /var/www/owncloud/data/owncloud.log

  install-app:
    image: owncloudci/php:latest
    commands:
      - cd /var/www/owncloud/apps/user_ldap
      - make
      - cd /var/www/owncloud/
      - php occ a:l
      - php occ a:e user_ldap
      - php occ a:e testing
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=server
      - php occ config:system:set trusted_domains 2 --value=federated
      - php occ log:manage --level 0

  run-integration-tests:
    image: owncloudci/php:latest
    pull: true
    environment:
      - BROWSER=chrome #chrome or firefox
    commands:
      - php -f ./tests/Integration/Lib/${INTEGRATION_TEST_SCRIPT}

matrix:
  INTEGRATION_TEST_SCRIPT:
    - IntegrationTestAccessGroupsMatchFilter.php
    - IntegrationBackupServer.php
    - User/IntegrationTestUserAvatar.php
    - User/IntegrationTestUserDisplayName.php
    - IntegrationTestBackupServer.php
    - IntegrationConnect.php
    - IntegrationTestBatchApplyUserAttributes.php
    - IntegrationTestConnect.php
    - IntegrationTestCountUsersByLoginName.php
    - IntegrationTestFetchUsersByLoginName.php
    - IntegrationTestPaging.php
    
